services:
  - mysql
dist: precise
language: elixir
elixir:
  - 1.5.2
otp_release:
  - 19.3
before_script:
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix ecto.create
  - mix ecto.migrate
script:
  - mix test
