sudo: true
services:
  - mysql
before_install:
  - set -x
  - set -e
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo stop mysql-5.6 || echo "mysql-5.6 not stopped"
  - sudo  mysqld_safe --skip-grant-tables &
  - sleep 4
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo kill -9 `sudo cat /var/lib/mysql/mysqld_safe.pid`
  - sudo kill -9 `sudo cat /var/run/mysqld/mysqld.pid`
  - sudo service mysql restart
  - sleep 4
language: elixir
elixir:
  - 1.5.2
otp_release:
  - 19.3
before_script:
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix ecto.create
script:
  - mix test
